version: "3.3"
services:
  hdfs-namenode:
    build: 
      context: .
      labels:
        zenoss.zing.commit-sha: ${COMMIT_SHA:-none}
        zenoss.zing.pull-request: ${PULL_REQUEST:-none}
        zenoss.zing.branch_name: ${GIT_BRANCH:-none}
        zenoss.zing.build_number: ${BUILD_ID:-none}
        zenoss.zing.build_url: ${BUILD_URL:-none}
    image: ${SERVICE_IMAGE}:${IMAGE_TAG:-dev}
    command: namenode
    environment:
      CLUSTER_NAME: hdfs-namenode
      CONFIG_TYPE: dev
    ports:
    - 50070:50070 # NameNode WebUI
    volumes:
    - hdfs_nn:/data/hdfs/nn:rw
  hdfs-datanode:
    image: ${SERVICE_IMAGE}:${IMAGE_TAG:-dev}
    command: datanode
    environment:
      CLUSTER_NAME: hdfs-namenode
      CONFIG_TYPE: dev
    volumes:
    - hdfs_dn:/data/hdfs/dn:rw
volumes:
  hdfs_dn: {}
  hdfs_nn: {}
